### ISSUE TITLE
Sonic Mania

### ISSUE THREAD

**Issue by emberavenge** [TurtleMan64/SADX-SA2-Input-Display#1]
Regarding the application reading the inputs from Sonic Mania, basically when I press the b button the input display reads all the inputs and says that i'm pressing all of the buttons, when in reality i'm just pressing the b button. Sometimes it displays buttons when i'm not even pressing them

Like in this image, for example.
![image](https://user-images.githubusercontent.com/61599413/76587810-dc8f4a80-64c3-11ea-946a-07e053e810c1.png)

**Comment by TurtleMan64** [comment]
Yeah, Mania has been updated since I added it to the input display, so some addresses probably changed. I'll look into this tonight.
